### ISSUE TITLE
No longer working

### ISSUE THREAD

**Issue by dolch8** [ijgnd/anki21__reviewer_Add_Tag_and_Move#1]
I'm running Anki 2.1.20 on Mac OS 10.14.6 (Mojave)

The hotkeys are no longer performing any actions. The add_tags_and_change_deck function stopped working several weeks ago (after updating to anki 2.1.20, I believe) and the just_change_deck function stopped working a couple of days ago (despite no updates or changes). 

I have tried reinstalling both the add-on and Anki as well as trying several different configurations in the config menu to see if it was a specific tag or deck causing the issue. 

Have you run into any issues like this? Any ideas on how to fix?

**Comment by ijgnd** [comment]
the default shortcut "7" for "Just_add_tag__hotkey" no longer works in 2.1.20 because  Anki 2.1.20 uses it to fastforward audio.

after changing it the add-on worked for me.

I updated the add-on and did some cosmetic changes. to make sure I did not introduce a bug by accident: can you update and try again?

when add-ons stop working it's usually a conflict. That means the same shortcut is set in two places. Then none will work.

So I would change the shortcuts in your config that don't work and restart. If this doesn't help: Maybe disable all addons except for "Add_Tag_and_Move". If it works then: reenable half of your add-ons, restart and try again. If it works enable half of the reaming, restart and try again. With a few starts you should find the bad interactions.

If the add-on alone does not work for you:  from the main window click on Help->About. In the window that opens click the "Copy Debug Info" Button and share the copied text.

**Comment by dolch8** [comment]
I feel so silly for not thinking of Anki taking over more hotkeys! Thank you so much; it works perfectly now that I assigned different keys to the addon.
